typedef struct Tree Tree;
Tree* insertTreeNode(Tree* root, int key);
Tree* fillTree(Tree* node, int key);
void upperCase(char name[]);
Tree* editTree(Tree* root, int key);
Tree* deleteTreeNode(Tree* root, int key);
void deleteTree(Tree* root);
Tree* balanceTree(Tree* root);
int hDifference(Tree* root);
Tree* rotationL(Tree* root);
Tree* rotationR(Tree* root);
int	treeHeight(Tree* root);
int treeSize(Tree* root);
void printTree(Tree* node, int tabs);
void printSorted(Tree* node);
int biggest(Tree* root);
void saveData(Tree* root, FILE* file);
Tree* loadTree(Tree* root);
Tree* loadNode(Tree* root, FILE* file, int key);
int findKey(Tree* root, int key);
char* getName(Tree* root, int key);
float getPrice(Tree* root, int key);
